#ifndef __AGIP_H__
#define __AGIP_H__

#include <AGIPBindYT.h>
#include <AGIPUserAuthADID.h>
#include <AGIPUserDataReport.h>
#include <AGIPGWDataReportYT.h>
#include <AGIPPromoterUserList.h>
#include <AGIPBind.h>
#include <AGIPCreateOrUpdateUser.h>
#include <AGIPCreateRole.h>
#include <AGIPDeleteRole.h>
#include <AGIPHandset.h>
#include <AGIPRoleList.h>
#include <AGIPSerialNOVerify.h>
#include <AGIPUnbind.h>
#include <AGIPUserEnterGame.h>
#include <AGIPUserItemList.h>
#include <AGIPUserItemMinus.h>
#include <AGIPUserLogin.h>
#include <AGIPUserLogout.h>
#include <AGIPUserUseProduct.h>
#include <AGIPGWDataReport.h>
#include <AGIPUserBalanceInfo.h>
#include <AGIPUserDrawBalance.h>
#include <AGIPUserFastCharge.h>
#include <AGIPUserCharge.h>
#include <AGIPUserChargeAudit.h>
#include <AGIPUserIBPay.h>
#include <AGIPUserIBPayAudit.h>
#include <AGIPRoleStateQuery.h>
#include <AGIPUserAuth.h>
#include <AGIPRoleEnterGame.h>
#include <AGIPPlainText.h>
#include <AGIPJointAuthen.h>
#include <AGIPPfCharge.h>
#include <AGIPPfOrderQuery.h>
#include <AGIPPfGwDataQuery.h>
#include <AGIPGwSignIn.h>
#include <AGIPUserStateQuery.h>
#include <AGIPCreateGroup.h>
#include <AGIPPasswordVerify.h>
#include <AGIPDeleteGroup.h>
#include <AGIPRegistService.h>
#include <AGIPUnregistService.h>
#include <AGIPUserCashExchange.h>
#include <AGIPUserCashExchangeAudit.h>
#include <AGIPPayListQuery.h>
#include <AGIPPayDetailDemand.h>

#endif

