#ifndef _PRIVILEGE_H_
#define _PRIVILEGE_H_

enum EMPRIVILEGE
{
	EM_PRIV_START					= 0,
	EM_PRIV_RELOAD_RANK 			= 1,
	EM_PRIV_QUERY_ROLE_INFO 		= 2,
	EM_PRIV_UPDATE_ROLE_INFO		= 3,
	EM_PRIV_QUERY_ROLE_BASIC		= 4,
	EM_PRIV_QUERY_ROLE_SKILL		= 5,
	EM_PRIV_QUERY_ROLE_BUFF			= 6,
	EM_PRIV_QUERY_ROLE_CDGROUP		= 7,
	EM_PRIV_QUERY_ROLE_PACKAGE		= 8,
	EM_PRIV_QUERY_ROLE_EQUIPMENT	= 9,
	EM_PRIV_QUERY_ROLE_STORAGE		= 10,
	EM_PRIV_QUERY_ROLE_PVP			= 11,
	EM_PRIV_QUERY_ROLE_TITLE		= 12,
	EM_PRIV_QUERY_ROLE_ACTIVITY		= 13,
	EM_PRIV_QUERY_ROLE_TALENT		= 14,
	EM_PRIV_QUERY_ROLE_MW			= 15,
	EM_PRIV_QUERY_ROLE_LIFESKILL	= 16,
	EM_PRIV_QUERY_ROLE_STATISTIC	= 17,
	EM_PRIV_QUERY_ROLE_TASK			= 18,
	EM_PRIV_QUERY_ROLE_TASK_PACKAGE = 19,
	EM_PRIV_QUERY_ROLE_MONSTER_RECORD = 20,
	EM_PRIV_QUERY_ROLE_TELE_POS		= 21,
	EM_PRIV_QUERY_ROLE_WIZARD		= 22,
	EM_PRIV_QUERY_ROLE_FRIEND		= 23,
	EM_PRIV_QUERY_ROLE_REPETION		= 24,
	EM_PRIV_QUERY_ROLE_CLIENT		= 25,

	EM_PRIV_UPDATE_ROLE_BASIC		= 26,
	EM_PRIV_UPDATE_ROLE_SKILL		= 27,
	EM_PRIV_UPDATE_ROLE_BUFF		= 28,
	EM_PRIV_UPDATE_ROLE_CDGROUP		= 29,
	EM_PRIV_UPDATE_ROLE_PACKAGE		= 30,
	EM_PRIV_UPDATE_ROLE_EQUIPMENT	= 31,
	EM_PRIV_UPDATE_ROLE_STORAGE		= 32,
	EM_PRIV_UPDATE_ROLE_PVP			= 33,
	EM_PRIV_UPDATE_ROLE_TITLE		= 34,
	EM_PRIV_UPDATE_ROLE_ACTIVITY	= 35,
	EM_PRIV_UPDATE_ROLE_TALENT		= 36,
	EM_PRIV_UPDATE_ROLE_MW			= 37,
	EM_PRIV_UPDATE_ROLE_LIFESKILL	= 38,
	EM_PRIV_UPDATE_ROLE_STATISTIC	= 39,
	EM_PRIV_UPDATE_ROLE_TASK		= 40,
	EM_PRIV_UPDATE_ROLE_TASK_PACKAGE		= 41,
	EM_PRIV_UPDATE_ROLE_MONSTER_RECORD		= 42,
	EM_PRIV_UPDATE_ROLE_TELE_POS	= 43,
	EM_PRIV_UPDATE_ROLE_WIZARD		= 44,
	EM_PRIV_UPDATE_ROLE_FRIEND		= 45,
	EM_PRIV_UPDATE_ROLE_REPETION	= 46,
	EM_PRIV_UPDATE_ROLE_CLIENT		= 47,

	EM_PRIV_ENABLE_BLACKLIST		= 48,
	EM_PRIV_DISABLE_BLACKLIST		= 49,
	EM_PRIV_ADD_BLACKLIST			= 50,
	EM_PRIV_DEL_BLACKLIST			= 51,
	EM_PRIV_CLEAR_BLACKLIST			= 52,
	EM_PRIV_RELOAD_BLACKLIST		= 53,

	EM_PRIV_KICKOFF_ROLE			= 54,
	EM_PRIV_SHUTUP_ACCOUNT			= 55,
	EM_PRIV_UNSHUTUP_ACCOUNT		= 56,
	EM_PRIV_TRANSFER_ROLE			= 57,
	EM_PRIV_SHOW_BLACKLIST			= 58,

	EM_PRIV_QUERY_LEVEL_BY_TOP		= 59,		// 查询等级排行
	EM_PRIV_QUERY_LEVEL_BY_LOG		= 60,		// 查询某玩家升级日志
	EM_PRIV_END						= 90,
};


#endif
