#pragma once

#include "LogicInterface.h"
#include "lua.h"

// ********************************************************************** //
// CProLuaInterface
// ********************************************************************** //

class WTLOGIC_API CProLuaInterface
{
public:
	static int Debug( lua_State* pLua );
	static int GetNpcType( lua_State* pLua );
	static int GetRemainPoint( lua_State* pLua );
	static int GetExp( lua_State* pLua );
	static int GetLevel( lua_State* pLua );
	static int GetMetier( lua_State* pLua );
	static int GetItemBasicInfo( lua_State* pLua );
	static int GetStorageReleaseIndex( lua_State* pLua );
	static int GetStorageItemByIndex( lua_State* pLua );
	static int GetBaggageReleaseIndex( lua_State* pLua );
	static int GetItemByIndex( lua_State* pLua );
	static int GetTaskBaggageReleaseIndex( lua_State* pLua );
	static int GetTaskItemByIndex( lua_State* pLua );
	static int GetEquipObjectInfo( lua_State* pLua );
	static int GetPetEggItemTplInfo( lua_State* pLua );
	static int GetPetFoodItemTplInfo( lua_State* pLua );
	static int GetReturnItemTplInfo( lua_State* pLua );
	static int GetTeleportItemTplInfo( lua_State* pLua );
	static int GetBookItemTplInfo( lua_State* pLua );
	static int GetRelifeItemTplInfo( lua_State* pLua );
	static int GetUpgLeastItemTplInfo( lua_State* pLua );
	static int GetUpgLuckItemTplInfo( lua_State* pLua );
	static int GetExpItemTplInfo( lua_State* pLua );
	static int GetShoutItemTplInfo( lua_State* pLua );
	static int GetPhysicItemTplInfo( lua_State* pLua );
	static int GetSkillItemTplInfo( lua_State* pLua );
	static int GetFashionTemplateInfo( lua_State* pLua );
	static int GetArmorTemplateInfo( lua_State* pLua );
	static int GetWeaponTemplateInfo( lua_State* pLua );
	static int GetProNum( lua_State* pLua );
	static int GetProID( lua_State* pLua );
	static int GetPhysID( lua_State* pLua );
	static int GetProDef( lua_State* pLua );
	static int GetProPer( lua_State* pLua );
	static int GetUpgPer( lua_State* pLua );
	static int GetStr( lua_State* pLua );
	static int GetSta( lua_State* pLua );
	static int GetCon( lua_State* pLua );
	static int GetWis( lua_State* pLua );
	static int GetSpr( lua_State* pLua );
	static int GetCurAP( lua_State* pLua );
	static int GetCurHP( lua_State* pLua );
	static int GetCurMP( lua_State* pLua );
	static int GetMaxHP( lua_State* pLua );
	static int GetMaxMP( lua_State* pLua );
	static int GetPAttackLower( lua_State* pLua );
	static int GetPAttackUpper( lua_State* pLua );
	static int GetMAttackLower( lua_State* pLua );
	static int GetMAttackUpper( lua_State* pLua );
	static int GetNormalHitrate( lua_State* pLua );
	static int GetNormalDuck( lua_State* pLua );
	static int GetSkillDuck( lua_State* pLua );
	static int GetPDefence( lua_State* pLua );
	static int GetMDefence( lua_State* pLua );
	static int GetPResist( lua_State* pLua );
	static int GetMResist( lua_State* pLua );
	static int GetDeathValue( lua_State* pLua );
	static int GetDeathRate( lua_State* pLua );
	static int GetAbnResist( lua_State* pLua );
	static int GetFireResist( lua_State* pLua );
	static int GetWaterResist( lua_State* pLua );
	static int GetWindResist( lua_State* pLua );
	static int GetLightResist( lua_State* pLua );
	static int GetEarthResist( lua_State* pLua );
	static int GetShadowResist( lua_State* pLua );
	static int GetEntityHP( lua_State* pLua );
	static int GetEntityMP( lua_State* pLua );
	static int GetEntityAP( lua_State* pLua );
	static int GetEntityLevel( lua_State* pLua );
	static int GetEntityMetier( lua_State* pLua );
	static int GetEntityPKValue( lua_State* pLua );
	static int GetEntityPKStatus( lua_State* pLua );
	static int GetSkillByIndex( lua_State* pLua );
	static int GetSkillTree( lua_State* pLua );
	static int AbortTask( lua_State* pLua );
	static int GetSkillTemplateInfo( lua_State* pLua );
	static int GetSkillPoint( lua_State* pLua );
	static int GetSkillNumber( lua_State* pLua );
	static int GetSkillCooldown( lua_State* pLua );
	static int GetSkillLevel( lua_State* pLua );
	static int GetIncSkillLevel( lua_State* pLua );
	static int GetSellItemID( lua_State* pLua );
	static int GetSellPageName( lua_State* pLua );
	static int ResetAllSP( lua_State* pLua );
	static int ResetSingleSP( lua_State* pLua );
	static int ClickSP( lua_State* pLua );
	static int ResetAllPP( lua_State* pLua );
	static int ResetSinglePP( lua_State* pLua );
	static int ClickPP( lua_State* pLua );
	static int IsSPResetable( lua_State* pLua );
	static int GetNpcTalk( lua_State* pLua );
	static int GetNpcSell( lua_State* pLua );
	static int HasMailService( lua_State* pLua );
	static int GetUpgService( lua_State* pLua );
	static int MoveItem( lua_State* pLua );
	static int EquipItem( lua_State* pLua );
	static int UnEquipItem( lua_State* pLua );
	static int UseSkill( lua_State* pLua );
	static int IsResetable( lua_State* pLua );
	static int ValidNormalAttack( lua_State* pLua );
	static int GetNormalAttackRange( lua_State* pLua );
	static int NormalAttack( lua_State* pLua );
	static int PickItem( lua_State* pLua );
	static int GetMoney( lua_State* pLua );
	static int GetEquipment( lua_State* pLua );
	static int GetEntityEquipment( lua_State* pLua );
	static int ClickNpc( lua_State* pLua );
	static int ClickShop( lua_State* pLua );
	static int ClickMail( lua_State* pLua );
	static int ClickUpg( lua_State* pLua );
	static int CloseDialog( lua_State* pLua );
	static int PurchaseItem( lua_State* pLua );
	static int SellItem( lua_State* pLua );
	static int ThrowItem( lua_State* pLua );
	static int UseItem( lua_State* pLua );
	static int ProItem( lua_State* pLua );
	static int ProPhys( lua_State* pLua );
	static int UpgItem( lua_State* pLua );
	static int UpgAdd( lua_State* pLua );
	static int UpgDel( lua_State* pLua );
	static int UpgClose( lua_State* pLua );
	static int GetUpg( lua_State* pLua );
	static int ThrowMoney( lua_State* pLua );
	static int GetNpcTip( lua_State* pLua );
	static int GetNpcTaskCount( lua_State* pLua );
	static int GetNpcTask( lua_State* pLua );
	static int GetNextTask( lua_State* pLua );
	static int IsTaskAcceptable( lua_State* pLua );
	static int GetDialogSubOptionID( lua_State* pLua );
	static int GetDialogNpcTalk( lua_State* pLua );
	static int GetDialogOptionText( lua_State* pLua );
	static int GetDialogOptionType( lua_State* pLua );
	static int GetDialogParentDialogID( lua_State* pLua );
	static int GetTaskActiveDialogID( lua_State* pLua );
	static int GetTaskBeginDialogID( lua_State* pLua );
	static int GetTaskCompleteDialogID( lua_State* pLua );
	static int GetDialogFuncCode( lua_State* pLua );
	static int GetTaskName( lua_State* pLua );
	static int SelectOption( lua_State* pLua );
	static int GetTaskState( lua_State* pLua );
	static int GetTaskCount( lua_State* pLua );
	static int GetTaskByIndex( lua_State* pLua );
	static int GetTaskCompleteOgre( lua_State* pLua );
	static int GetTaskCompleteItem( lua_State* pLua );
	static int GetTaskCompleteMoney( lua_State* pLua );
	static int GetTaskCompleteLevel( lua_State* pLua );
	static int GetTaskCompleteTalkNpc( lua_State* pLua );
	static int GetTaskCompleteRegion( lua_State* pLua );
	static int SetShortcut( lua_State* pLua );
	static int GetShortcut( lua_State* pLua );
	static int GetOgreName( lua_State* pLua );
	static int GetNpcName( lua_State* pLua );
	static int Relive( lua_State* pLua );
	static int GetItemStreamByIndex( lua_State* pLua );
	static int GetEquipmentStream( lua_State* pLua );
	static int GetItemFromStream( lua_State* pLua );
	static int GetEquipLevel( lua_State* pLua );
	static int GetEquipProducer( lua_State* pLua );
	static int GetEquipSlotNumber( lua_State* pLua );
	static int GetEquipProperty( lua_State* pLua );
	static int GetEquipSlotProperty( lua_State* pLua );
	static int GetBuffNumber( lua_State* pLua );
	static int GetBuffObject( lua_State* pLua );
	static int IsLocked( lua_State* pLua );
	static int GetRolePersonalInfoByID( lua_State* pLua );
	static int GetRolePersonalInfoByName( lua_State* pLua );
	static int SetRolePersonalInfo( lua_State* pLua );
	static int GetEntityTplID( lua_State* pLua );
	static int GetEntityWalkSpeed( lua_State* pLua );
	static int GetEntityRunSpeed( lua_State* pLua );

	static int GetEntityTplID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int SetRolePersonalInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetRolePersonalInfoByName( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetRolePersonalInfoByID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int IsLocked( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetItemStreamByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipmentStream( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetItemFromStream( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipProducer( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipSlotNumber( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipProperty( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipSlotProperty( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetBuffNumber( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetBuffObject( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int Relive( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int AbortTask( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCount( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteOgre( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteMoney( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteRegion( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteTalkNpc( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNextTask( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int IsTaskAcceptable( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskState( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int SelectOption( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogOptionText( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogOptionType( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogParentDialogID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogFuncCode( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskName( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskCompleteDialogID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskBeginDialogID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskActiveDialogID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogSubOptionID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDialogNpcTalk( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcTaskCount( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcTask( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcTip( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcTalk( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetShortcut( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int SetShortcut( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcSell( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int HasMailService( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetUpgService( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ThrowMoney( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ThrowItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int SellItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int PurchaseItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickNpc( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickShop( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickMail( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickUpg( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickStorage( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int CloseDialog( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityEquipment( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipment( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int Debug( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNpcType( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetRemainPoint( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetExp( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMetier( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetItemBasicInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetStorageReleaseIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetStorageItemByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetBaggageReleaseIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetItemByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskBaggageReleaseIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTaskItemByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEquipObjectInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPetEggItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPetFoodItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetReturnItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetTeleportItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetBookItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetRelifeItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetUpgLeastItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetUpgLuckItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetExpItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetShoutItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPhysicItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillItemTplInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetFashionTemplateInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetArmorTemplateInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetWeaponTemplateInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetProNum( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetProID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPhysID( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetProPer( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetUpgPer( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetProDef( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetStr( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSta( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetCon( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetWis( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSpr( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetCurAP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetCurHP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetCurMP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMaxHP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMaxMP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPAttackLower( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPAttackUpper( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMAttackLower( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMAttackUpper( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNormalHitrate( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetNormalDuck( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillDuck( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPDefence( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMDefence( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetPResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDeathValue( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetDeathRate( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetAbnResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetFireResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetWaterResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetWindResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetLightResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEarthResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetShadowResist( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityHP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityMP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityAP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityMetier( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityGender( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityPKValue( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityPKStatus( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillByIndex( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillTree( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillTemplateInfo( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillPoint( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillNumber( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillCooldown( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetSkillLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetIncSkillLevel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetMoney( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ResetAllSP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ResetSingleSP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickSP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ResetAllPP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ResetSinglePP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ClickPP( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int IsSPResetable( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int PickItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int MoveItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int EquipItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UseItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ProItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int ProPhys( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UpgItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UpgAdd( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UpgDel( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UpgClose( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetUpg( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UnEquipItem( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int UseSkill( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int IsResetable( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int NormalAttack( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityWalkSpeed( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
	static int GetEntityRunSpeed( int vLogicID, const CEventSink& rInput, CEventSink& rOutput );
};
