#pragma once


enum STALL_STATE
{
	STALL_COMM = 0x0001,
	STALL_ADD  = 0x0002,
	STALL_TRADE= 0x0003,
};

#define SEL_GOODS_COUNT_MAX		( 20 )
#define BUY_GOODS_COUNT_MAX		( 20 )
#define STALL_NAME_LEN_MAX		( 100 )
#define STALL_MAX_LENGTH		( 10 )
#define STALL_MSG_LENGTH		( 100 )

#define STALL_MSG_ERR_UNKNOWN				( 0x0000 )
#define STALL_MSG_PLAYER_NOTFOUND			( 0x0001 )
#define STALL_MSG_PLAYER_NOTISSTORE			( 0x0002 )
#define STALL_MSG_IS_STOREKEEPER			( 0x0003 )
#define STALL_MSG_NOT_ADD					( 0x0004 )
#define STALL_MSG_NOT_COMM					( 0x0005 )
#define STALL_MSG_COUNT_IS_ZERO				( 0x0006 )
#define STALL_MSG_NOT_LOOKER				( 0x0007 )
#define STALL_MAG_STOREKEEP_MSONEYLESS		( 0X0008 )
#define STALL_MSG_LOOKER_MONEYLESS			( 0X0009 )
#define STALL_MSG_STOREKEEP_BAG_LESS		( 0X000A )
#define STALL_MSG_LOOKER_BAG_LESS			( 0x000B )
#define STALL_MSG_STOREKEEP_ITEM_NOTFOUND	( 0x000C )
#define STALL_MSG_LOOKER_ITEM_NOTFOUND		( 0x000D )
#define STALL_MSG_ITEM_NOTFOUND				( 0x000E )
#define STALL_MSG_ITEM_ADD_NUM_LESS			( 0X000F )
#define STALL_MSG_FAR						( 0x0010 )
#define STALL_MSG_ITEM_LOCKED				( 0x0011 )
#define STALL_MSG_TRADE_COUNT_LESS			( 0x0012 )




