#pragma once
#if 0
/******************************************************************************
   版权所有 (C ), 2008-2018, 蓝港在线（北京）科技有限公司

******************************************************************************
  文件名          : sceneobj_define.h
  版本号          : 1.0
  作者            : ZHL
  生成日期        : 2008-06-26
  最近修改        : 
  功能描述        : 定义场景服务器各种游戏对象预分配数量
  函数列表        : 
  修改历史        : 
  1 日期          : 2008-06-26
    作者          : ZHL
    修改内容      : 生成
*******************************************************************************/
#endif



// 下面定义服务器负载
#ifdef _DEBUG_
	#define SERVER_CAP_PLAYER				70		// 玩家最大人数
	#define SERVER_CAP_NPC_OGRE				18000	// 怪物最大数
#ifndef _FB_
	#define SERVER_CAP_NPC_FUNCNPC			(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_L_MAP_OBJECT)*10 // 功能NPC最大数
#else
	#define SERVER_CAP_NPC_FUNCNPC			( SERVER_CAP_REPETION_OBJECT )*5	// 功能NPC最大数
#endif
	#define SERVER_CAP_NPC_CHARACTER		( SERVER_CAP_NPC_OGRE + SERVER_CAP_NPC_FUNCNPC )
	#define SERVER_CAP_NPC_PEDAL			300		// 踏板最大数
	#define SERVER_CAP_NPC_ITEM				SERVER_CAP_PLAYER * 10	// 道具最大数
	#define SERVER_CAP_NPC_PET				(SERVER_CAP_PLAYER)	// 宠物最大数
	#define SERVER_CAP_NPC					(SERVER_CAP_NPC_PET+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PEDAL+SERVER_CAP_NPC_ITEM)	// NPC最大数
	#define SERVER_CAP_ITEM_BOOK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPUPG		50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EXP				1 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_PHYSIC			60 * SERVER_CAP_PLAYER 
	#define SERVER_CAP_ITEM_RELIFE			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RETURN			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SKILL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TELEPORT		50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPMENT		100 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TASK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_STUFF			150 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_NOTE			50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RUNE			50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_JEWEL			50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANBUG			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANEGG			50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SCROLL			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CARD			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CALL			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_FUNC			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SHOUT           SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_AUTOSHOUT       SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_KITBAG			SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_GIFTBAG			SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_MAGICWEAPON		SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_SKILLBOOK		SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_MAILCACHE			(SERVER_CAP_PLAYER*30)		// 邮件缓存最大值
	#define SERVER_CAP_ITEM_QUESTIONPAPER   (SERVER_CAP_PLAYER*10)		// 题卷最大数
	#define SERVER_CAP_ITEM_REMOVE			(SERVER_CAP_PLAYER*50)		// 摘除符
	#define SERVER_CAP_ITEM_CHANGE			(SERVER_CAP_PLAYER*50)		// 转换符
	#define SERVER_CAP_ITEM_TOKEN			(SERVER_CAP_PLAYER*20)		// 令牌
	#define	SERVER_CAP_ITEM_MINE			(SERVER_CAP_PLAYER*20)		// 藏宝图
	#define SERVER_CAP_NPC_COLLECT			(1000)		// 采集npc
	#define SERVER_CAP_SHARE_SEEN_PLAYER	(SERVER_CAP_PLAYER+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_ITEM)*3
	#define SERVER_CAP_SHARE_SEEN_CHARNPC	(SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PET)*3
	#define SERVER_CAP_SHARE_SEEN_STATICNPC	1
	#define SERVER_CAP_RELIVEPOSITION		(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_L_MAP_OBJECT) // 复活点 
	#define SERVER_CAP_MAGICSTONE			(SERVER_CAP_PLAYER*20) 
	#define SERVER_CAP_LIFESKILLSCROLL		(SERVER_CAP_PLAYER*20)
	#define SERVER_CAP_FAMILYINFO			500							// 场景上总共可能的家族个数,因为只有家族成员在本场景时才会建立，所以数量暂取为最大家族数量的四分之一  
	#define	SERVER_CAP_ITEM_REDPAPER		(SERVER_CAP_PLAYER*20)		// 红包  
	#define	SERVER_CAP_ITEM_VIP				(SERVER_CAP_PLAYER*20)		// 会员道具 
	#define	SERVER_CAP_ITEM_CLEAN			(SERVER_CAP_PLAYER*20)		// 洗点道具 
	#define SERVER_CAP_ITEM_LEAGUEBAG		(SERVER_CAP_PLAYER*20)		// 家族军团特供物品
	#define SERVER_CAP_REDSTONECONTROLLER	(1000)						// 内丹控制器的个数
	#define SERVER_CAP_ITEM_INVITATION		(SERVER_CAP_PLAYER*20)		// 请帖  
	#define SERVER_CAP_MARRIAGEINFO			(SERVER_CAP_PLAYER)			// 婚姻信息
	#define SERVER_CAP_ITEM_SYSINVITATION		(SERVER_CAP_PLAYER*20)		// 请帖 
	#define SERVER_CAP_ITEM_BLACKPILLS			(SERVER_CAP_PLAYER*20)		// 黑狗丸 
	#define SERVER_CAP_ITEM_EXPCONTAINER	(SERVER_CAP_PLAYER*10)		// 修炼经验丹
	#define SERVER_CAP_ITEM_EXPPILLS	 	(SERVER_CAP_PLAYER*10)		// 经验丹 	
#ifndef _FB_ 
	#define SERVER_CAP_L_MAP_OBJECT			12
	#define SERVER_CAP_M_MAP_OBJECT			40
	#define SERVER_CAP_S_MAP_OBJECT			34
	#define SERVER_CAP_MAP_TPL				(SERVER_CAP_L_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT)
#else
	#define SERVER_CAP_L_MAP_OBJECT			18
	#define SERVER_CAP_M_MAP_OBJECT			18
	#define SERVER_CAP_S_MAP_OBJECT			300
	#define SERVER_CAP_MAP_TPL				70
#endif
	#define SERVER_CAP_REPETION_OBJECT		( 50 )
	#define SERVER_CAP_NPCPOLICY			(SERVER_CAP_NPC_OGRE + SERVER_CAP_NPC_FUNCNPC) // 怪物+功能NPC
	#define SERVER_CAP_PEDAL				(SERVER_CAP_PLAYER/6*8)+SERVER_CAP_NPC_PEDAL	// 陷阱+传送点最大数  
	#define SERVER_CAP_ITEM_HORSE			SERVER_CAP_PLAYER * 4
	#define SERVER_CAP_ITEM_BINDSTONE       SERVER_CAP_PLAYER * 10
	#define SERVER_CAP_SHARE_CELLENTITY		(SERVER_CAP_PLAYER+SERVER_CAP_NPC)	// 站在所有cell里面的总实体数
	#define SERVER_CAP_MAXBUGLESPERKER      SERVER_CAP_PLAYER*20
#ifndef _FB_
	#define SERVER_CAP_STOREBOX				( 10 *(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT) )
#else
	#define SERVER_CAP_STOREBOX				( 10 * SERVER_CAP_REPETION_OBJECT )
#endif
	#define SERVER_CAP_EXPREDSTONE			100											// 内丹的数量
	#define SERVER_CAP_SESSION				(SERVER_CAP_PLAYER*8)						// Session 数
#ifndef _FB_
	#define SERVER_CAP_BLOCK				( 10*(SERVER_CAP_L_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT) )										// 动态阻挡
#else
	#define SERVER_CAP_BLOCK				( 50 * SERVER_CAP_REPETION_OBJECT )
#endif
	#define SERVER_CAP_IBTRANS 				(SERVER_CAP_PLAYER*4)	
	#define SERVER_CAP_GHOST				SERVER_CAP_PLAYER
	#define SERVER_CAP_STALLRECORD				10				// 在途(某一时刻正在进行的)的摆摊交易记录
	#define SERVER_CAP_FUNCTRANS			(SERVER_CAP_PLAYER*4)						//功能付费对象
#else  // relase define

#ifndef _FB_
	#define SERVER_CAP_PLAYER				2000	// 玩家最大人数
	#define SERVER_CAP_NPC_OGRE				18000	// 怪物最大数
	#define SERVER_CAP_NPC_FUNCNPC			(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_L_MAP_OBJECT)*10// 功能NPC最大数
	#define SERVER_CAP_MAILCACHE			(SERVER_CAP_PLAYER*20)		// 邮件缓存最大值
	#define SERVER_CAP_NPC_COLLECT			(1000)		// 采集npc
	#define SERVER_CAP_REDSTONECONTROLLER	(10000)		// 内丹控制器的个数
	#define SERVER_CAP_NPC_CHARACTER		( SERVER_CAP_NPC_OGRE + SERVER_CAP_NPC_FUNCNPC )
	#define SERVER_CAP_NPC_PEDAL			300		// 踏板最大数
	#define SERVER_CAP_NPC_ITEM				(SERVER_CAP_PLAYER * 10) 	// 道具最大数
	#define SERVER_CAP_NPC_PET				(SERVER_CAP_PLAYER)	// 宠物最大数
	#define SERVER_CAP_NPC					(SERVER_CAP_NPC_PET+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PEDAL+SERVER_CAP_NPC_ITEM)	// NPC最大数
	#define SERVER_CAP_ITEM_BOOK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPUPG		20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EXP				1 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_PHYSIC			50 * SERVER_CAP_PLAYER 
	#define SERVER_CAP_ITEM_RELIFE			15 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RETURN			15 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SKILL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TELEPORT		40 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPMENT		100 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TASK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_STUFF			50 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_NOTE			40 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RUNE			40 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_JEWEL			40 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANBUG			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANEGG			40 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SCROLL			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CARD			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CALL			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_FUNC			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SHOUT           SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_AUTOSHOUT       SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_KITBAG			SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_GIFTBAG			SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_MAGICWEAPON		SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_SKILLBOOK		SERVER_CAP_PLAYER * 20
	#define SERVER_CAP_ITEM_QUESTIONPAPER   (SERVER_CAP_PLAYER*10)		// 题卷最大数
	#define SERVER_CAP_ITEM_REMOVE			(SERVER_CAP_PLAYER*50)		// 摘除符
	#define SERVER_CAP_ITEM_CHANGE			(SERVER_CAP_PLAYER*50)		// 转换符
	#define SERVER_CAP_ITEM_TOKEN			(SERVER_CAP_PLAYER*20)		// 令牌
	#define	SERVER_CAP_ITEM_MINE			(SERVER_CAP_PLAYER*20)		// 藏宝图
	#define SERVER_CAP_SHARE_SEEN_PLAYER	(SERVER_CAP_PLAYER+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_ITEM)*3
	#define SERVER_CAP_SHARE_SEEN_CHARNPC	(SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PET)*3
	#define SERVER_CAP_SHARE_SEEN_STATICNPC	1
	#define SERVER_CAP_RELIVEPOSITION		(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_L_MAP_OBJECT) // 复活点 
	#define SERVER_CAP_MAGICSTONE			(SERVER_CAP_PLAYER*20) 
	#define SERVER_CAP_LIFESKILLSCROLL		(SERVER_CAP_PLAYER*20) 
	#define SERVER_CAP_FAMILYINFO			2500					// 场景上总共可能的家族个数,因为只有家族成员在本场景时才会建立，所以数量暂取为最大家族数量的四分之一  
	#define	SERVER_CAP_ITEM_REDPAPER		(SERVER_CAP_PLAYER*20)		// 红包  
	#define	SERVER_CAP_ITEM_VIP				(SERVER_CAP_PLAYER*20)		// 会员道具 
	#define	SERVER_CAP_ITEM_CLEAN			(SERVER_CAP_PLAYER*20)		// 洗点道具
	#define SERVER_CAP_ITEM_LEAGUEBAG		(SERVER_CAP_PLAYER*20)		// 家族军团特供物品
	#define SERVER_CAP_ITEM_INVITATION		(SERVER_CAP_PLAYER*20)		// 请帖
	#define SERVER_CAP_MARRIAGEINFO			(SERVER_CAP_PLAYER)			// 婚姻信息
	#define SERVER_CAP_ITEM_SYSINVITATION	(SERVER_CAP_PLAYER*20)		// 请帖
	#define SERVER_CAP_ITEM_BLACKPILLS		(SERVER_CAP_PLAYER*20)		// 黑狗丸
	#define SERVER_CAP_ITEM_EXPCONTAINER	(SERVER_CAP_PLAYER*10)		// 修炼经验丹
	#define SERVER_CAP_ITEM_EXPPILLS	 	(SERVER_CAP_PLAYER*10)		// 经验丹    	
	#define SERVER_CAP_L_MAP_OBJECT			6
	#define SERVER_CAP_M_MAP_OBJECT			40
	#define SERVER_CAP_S_MAP_OBJECT			34
	#define SERVER_CAP_MAP_TPL				(SERVER_CAP_L_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT)
	#define SERVER_CAP_STOREBOX				( 10 *(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT) )
	#define SERVER_CAP_BLOCK				( 10 *(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_S_MAP_OBJECT) )										// 动态阻挡
	#define SERVER_CAP_EXPREDSTONE			2000	// 内丹的数量
	#define SERVER_CAP_STALLRECORD			50		// 在途(某一时刻正在进行的)的摆摊交易记录，副本中没有摆摊
#else
	#define SERVER_CAP_PLAYER				1800	// 玩家最大人数
	#define SERVER_CAP_NPC_OGRE				30000	// 副本怪物最大数
	#define SERVER_CAP_NPC_FUNCNPC			( SERVER_CAP_REPETION_OBJECT )*5	// 功能NPC最大数
	#define SERVER_CAP_MAILCACHE			(SERVER_CAP_PLAYER)		// 邮件缓存最大值
	#define SERVER_CAP_NPC_COLLECT			(500)		// 采集npc
	#define SERVER_CAP_REDSTONECONTROLLER	(2000)		// 内丹控制器的个数
	#define SERVER_CAP_NPC_CHARACTER		( SERVER_CAP_NPC_OGRE + SERVER_CAP_NPC_FUNCNPC )
	#define SERVER_CAP_NPC_PEDAL			300		// 踏板最大数
	#define SERVER_CAP_NPC_ITEM				(SERVER_CAP_PLAYER * 10) 	// 道具最大数
	#define SERVER_CAP_NPC_PET				(SERVER_CAP_PLAYER)	// 宠物最大数
	#define SERVER_CAP_NPC					(SERVER_CAP_NPC_PET+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PEDAL+SERVER_CAP_NPC_ITEM)	// NPC最大数
	#define SERVER_CAP_ITEM_BOOK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPUPG		20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EXP				1 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_PHYSIC			40 * SERVER_CAP_PLAYER 
	#define SERVER_CAP_ITEM_RELIFE			5 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RETURN			5 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SKILL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TELEPORT		10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_EQUIPMENT		100 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_TASK			20 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_STUFF			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_NOTE			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_RUNE			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_JEWEL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANBUG			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_YUANEGG			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SCROLL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CARD			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_CALL			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_FUNC			10 * SERVER_CAP_PLAYER
	#define SERVER_CAP_ITEM_SHOUT           SERVER_CAP_PLAYER * 10
	#define SERVER_CAP_ITEM_AUTOSHOUT       SERVER_CAP_PLAYER * 5
	#define SERVER_CAP_ITEM_KITBAG			SERVER_CAP_PLAYER * 10
	#define SERVER_CAP_ITEM_GIFTBAG			SERVER_CAP_PLAYER * 10
	#define SERVER_CAP_ITEM_MAGICWEAPON		SERVER_CAP_PLAYER * 8
	#define SERVER_CAP_ITEM_SKILLBOOK		SERVER_CAP_PLAYER * 2
	#define SERVER_CAP_ITEM_QUESTIONPAPER   (SERVER_CAP_PLAYER*5)		// 题卷最大数
	#define SERVER_CAP_ITEM_REMOVE			(SERVER_CAP_PLAYER*10)		// 摘除符
	#define SERVER_CAP_ITEM_CHANGE			(SERVER_CAP_PLAYER*10)		// 转换符
	#define SERVER_CAP_ITEM_TOKEN			(SERVER_CAP_PLAYER*10)		// 令牌
	#define	SERVER_CAP_ITEM_MINE			(SERVER_CAP_PLAYER*10)		// 藏宝图
	#define SERVER_CAP_SHARE_SEEN_PLAYER	(SERVER_CAP_PLAYER+SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_ITEM)*3
	#define SERVER_CAP_SHARE_SEEN_CHARNPC	(SERVER_CAP_NPC_OGRE+SERVER_CAP_NPC_FUNCNPC+SERVER_CAP_NPC_PET)*3
	#define SERVER_CAP_SHARE_SEEN_STATICNPC	1
	#define SERVER_CAP_RELIVEPOSITION		(SERVER_CAP_S_MAP_OBJECT+SERVER_CAP_M_MAP_OBJECT+SERVER_CAP_L_MAP_OBJECT) // 复活点 
	#define SERVER_CAP_MAGICSTONE			(SERVER_CAP_PLAYER*10) 
	#define SERVER_CAP_LIFESKILLSCROLL		(SERVER_CAP_PLAYER*10) 
	#define SERVER_CAP_FAMILYINFO			2500					// 场景上总共可能的家族个数,因为只有家族成员在本场景时才会建立，所以数量暂取为最大家族数量的四分之一  
	#define	SERVER_CAP_ITEM_REDPAPER		(SERVER_CAP_PLAYER*10)		// 红包  
	#define	SERVER_CAP_ITEM_VIP				(SERVER_CAP_PLAYER*5)		// 会员道具 
	#define	SERVER_CAP_ITEM_CLEAN			(SERVER_CAP_PLAYER*5)		// 洗点道具
	#define SERVER_CAP_ITEM_LEAGUEBAG		(SERVER_CAP_PLAYER*10)		// 家族军团特供物品
	#define SERVER_CAP_ITEM_INVITATION		(SERVER_CAP_PLAYER*10)		// 请帖
	#define SERVER_CAP_MARRIAGEINFO			(SERVER_CAP_PLAYER)			// 婚姻信息
	#define SERVER_CAP_ITEM_SYSINVITATION	(SERVER_CAP_PLAYER*10)		// 请帖  
	#define SERVER_CAP_ITEM_BLACKPILLS		(SERVER_CAP_PLAYER*10)		// 黑狗丸 
	#define SERVER_CAP_ITEM_EXPCONTAINER	(SERVER_CAP_PLAYER*10)		// 修炼经验丹
	#define SERVER_CAP_ITEM_EXPPILLS	 	(SERVER_CAP_PLAYER*10)		// 经验丹
	#define SERVER_CAP_L_MAP_OBJECT			200
	#define SERVER_CAP_M_MAP_OBJECT			450
	#define SERVER_CAP_S_MAP_OBJECT			900
	#define SERVER_CAP_MAP_TPL				70
	#define SERVER_CAP_STOREBOX				( ( SERVER_CAP_REPETION_OBJECT ) * 5 )
	#define SERVER_CAP_BLOCK				( 10000 )
	#define SERVER_CAP_EXPREDSTONE			500	 // 内丹的数量
	#define SERVER_CAP_STALLRECORD			1				// 在途(某一时刻正在进行的)的摆摊交易记录，副本中没有摆摊
#endif

	#define SERVER_CAP_NPCPOLICY			(SERVER_CAP_NPC_OGRE + SERVER_CAP_NPC_FUNCNPC) // 怪物+功能NPC
	#define SERVER_CAP_PEDAL				(SERVER_CAP_PLAYER/6*8)+SERVER_CAP_NPC_PEDAL	// 陷阱+传送点最大数   
	#define SERVER_CAP_ITEM_HORSE			SERVER_CAP_PLAYER * 4
	#define SERVER_CAP_ITEM_BINDSTONE       SERVER_CAP_PLAYER * 10
    #define SERVER_CAP_REPETION_OBJECT		( 800 )
	#define SERVER_CAP_SHARE_CELLENTITY		(SERVER_CAP_PLAYER+SERVER_CAP_NPC)	// 站在所有cell里面的总实体数
	#define SERVER_CAP_MAXBUGLESPERKER      SERVER_CAP_PLAYER*20
					
	#define SERVER_CAP_SESSION				(SERVER_CAP_PLAYER*16)						// Session 数
	#define SERVER_CAP_IBTRANS 				(SERVER_CAP_PLAYER*4)	
	#define SERVER_CAP_GHOST				 SERVER_CAP_PLAYER
	#define SERVER_CAP_FUNCTRANS			(SERVER_CAP_PLAYER*4)						//功能付费对象
#endif // ! _DEBUG_

#ifndef _FB_ 
	#define MAX_MAP_CELL	(556)*(600)	// 每张地图上格子最大数
#else
	#define MAX_MAP_CELL	(300)*(310)	// 每张地图上格子最大数, 副本地图都较小
#endif //_FB_


#define MAX_TRAPS_NUM	SERVER_CAP_PLAYER * 8	// 最大陷阱数
#define MAX_MAP_PLAYER_PER		( SERVER_CAP_PLAYER )






// 全局对象类型
enum EGlobalObjType
{
	OBJTYPE_START ,			// start 
	OBJTYPE_ENTITY_PLAYER		= 1,
	OBJTYPE_ENTITY_FUNCNPC		= 2,
	OBJTYPE_ENTITY_PET			= 3,
	OBJTYPE_ENTITY_PEDAL		= 4,
	OBJTYPE_ENTITY_OGRE			= 5,
	OBJTYPE_ENTITY_MONEY		= 6,
	OBJTYPE_ENTITY_ITEM			= 7,
	OBJTYPE_CREATOR_OGRE		= 8,
	OBJTYPE_CREATOR_BOX			= 9,
	OBJTYPE_CREATOR_NPC			= 10,
	OBJTYPE_CREATOR_ITEM		= 11,
	OBJTYPE_CREATOR_PET			= 12,
	OBJTYPE_CREATOR_PEDAL		= 13,
	OBJTYPE_MAP_NPC				= 14,
	OBJTYPE_MAP_ENTITY			= 15,
	OBJTYPE_MAP_PEDAL			= 16,
	OBJTYPE_ITEM_BOOK			= 17,
	OBJTYPE_ITEM_SHOUT			= 18,
	OBJTYPE_ITEM_AUTOSHOUT		= 19,    
	OBJTYPE_ITEM_EQUIPUPG		= 20,
	OBJTYPE_ITEM_EXP			= 21,
	OBJTYPE_ITEM_PHYSIC			= 22,
	OBJTYPE_ITEM_RELIFE			= 23,
	OBJTYPE_ITEM_RETURN			= 24,
	OBJTYPE_ITEM_SKILL			= 25,
	OBJTYPE_ITEM_TELEPORT		= 26,
	OBJTYPE_ITEM_EQUIPMENT		= 27,
	OBJTYPE_ITEM_TASK			= 28,
	OBJTYPE_ITEM_SPECIAL_TASK	= 29,			
	OBJTYPE_ITEM_STUFF			= 30,
	OBJTYPE_ITEM_NOTE			= 31,
	OBJTYPE_ITEM_RUNE			= 32,
	OBJTYPE_ITEM_JEWEL			= 33,
	OBJTYPE_ITEM_YUANBUG		= 34,
	OBJTYPE_ITEM_YUANEGG		= 35,	
	OBJTYPE_TEAM				= 36,
	OBJTYPE_RELIVEPOSITION		= 37,
	OBJTYPE_MAP_L_OBJECT		= 38,
	OBJTYPE_MAP_M_OBJECT		= 39,
	OBJTYPE_MAP_S_OBJECT		= 40,
	OBJTYPE_POLICY_NPC			= 41,
	OBJTYPE_CHAT				= 42,
	OBJTYPE_TRADE				= 43,
	OBJTYPE_MAIL_MAILINFOR		= 44,
	OBJTYPE_MAIL_MAILCACHE		= 45,
	OBJTYPE_ITEM_HORSE			= 46,
	OBJTYPE_ITEM_BINDSTONE		= 47,
	OBJTYPE_TASKLIST			= 48,
	OBJTYPE_STALL				= 49,
	OBJTYPE_SESSION				= 50,
	OBJTYPE_ITEM_SCROLL			= 51,
	OBJTYPE_ENTITY_COLLECT		= 52,
	OBJTYPE_CREATOR_COLLECT		= 53,
	OBJTYPE_ITEM_CARD			= 54,
	OBJTYPE_REPETION			= 55,
	OBJTYPE_ENTITY_STOREBOX		= 56,
	OBJTYPE_DELAYACTION			= 57,
	OBJTYPE_RETURNPAPER			= 58,
	OBJTYPE_TELESYMBOL			= 59,
	OBJTYPE_ITEMSTOVE			= 60,
	OBJTYPE_ENTITY_EXPREDSTONE	= 61,
	OBJTYPE_ANSWERSTATUS		= 62, 
	OBJTYPE_ITEM_QUESTIONPAPER	= 63,
	OBJTYPE_ITEM_MINEMAP		= 64,
	OBJTYPE_ITEM_KITBAG			= 65,		
	OBJTYPE_ITEM_TOKEN			= 66,
	OBJTYPE_ENTITY_BLOCK		= 67,
	OBJTYPE_CREATOR_BLOCK		= 68,
	OBJTYPE_ITEM_CALL			= 69,
	OBJTYPE_ITEM_REMOVE			= 70,
	OBJTYPE_ITEM_CHANGE			= 71,
	OBJTYPE_ITEM_GIFTBAG		= 72,
	OBJTYPE_ITEM_MAGICSTONE		= 73,
	OBJTYPE_ITEM_LIFESKILLSCROLL= 74,			
	OBJTYPE_ITEM_MAGICWEAPON	= 75,
	OBJTYPE_ITEM_FUNCITEM		= 76,
	OBJTYPE_ITEM_SKILLBOOK		= 77,
	OBJTYPE_FAMILYINFO			= 78,
	OBJTYPE_IBTRANS				= 79,
	OBJTYPE_ITEM_REDPAPER		= 80,
	OBJTYPE_ACHIEVE				= 81,
	OBJTYPE_ITEM_VIP			= 82,
	OBJTYPE_ITEM_CLEAN			= 83,
	OBJTYPE_ITEM_LEAGUEBAG		= 84,
	OBJTYPE_REDSTONECONTROLLER	= 85,
	OBJTYPE_ITEM_INVITATION		= 86,
	OBJTYPE_MARRIAGEINFO		= 87,
	OBJTYPE_ITEM_SYSINVITATION	= 88,
	OBJTYPE_ITEM_BLACKPILLS		= 89,
	OBJTYPE_ITEM_EXPCONTAINER	= 90,
	OBJTYPE_ITEM_EXPPILLS		= 91,
	OBJTYPE_ENTITY_GHOST		= 92,
	OBJTYPE_CREATOR_GHOST		= 93,
	OBJTYPE_STALL_RECORD		= 94,
	OBJTYPE_FUNCTRANS			= 95,
	OBJTYPE_END,				// end
};


